import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Hostel-Management-System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css"/>
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700" rel="stylesheet" />
      </head>
      <body
        className="leading-normal tracking-normal text-white gradient"
      >
        {children}
      </body>
    </html>
  );
}
